services:
  backend:
    build:
      context: ./movies-backend
      dockerfile: Dockerfile
    image: movies-backend
    ports:
    - "3000:3000"
    environment:
    - OMDB_API_KEY=${OMDB_API_KEY}
    - DB_HOST=db
    - DB_USER=postgres
    - DB_PASSWORD=password
    - DB_DATABASE=movies_db
    - ES_HOST=http://elasticsearch:9200
    depends_on:
    - db
    - elasticsearch

  frontend:
    build:
      context: ./movies-frontend
      dockerfile: Dockerfile
    image: movies-frontend
    ports:
    - "3001:80"
    depends_on:
    - backend

  db:
    image: postgres:13
    environment:
    - POSTGRES_DB=movies_db
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=password
    volumes:
    - pgdata:/var/lib/postgresql/data
    ports:
    - "5432:5432"

  elasticsearch:
    image: elasticsearch:7.17.9
    environment:
    - discovery.type=single-node
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
    - esdata:/usr/share/elasticsearch/data
    ports:
    - "9200:9200"

volumes:
  pgdata:
  esdata: